### PR TITLE
Update bladebit.py

### PR DESCRIPTION
**Pull request by ApfelBirneKreis**
added the --check <n> argument with cudaplot 16G or 128G mode. Variable in plotman: Check_plots: true/false

### CODE REVIEW

**Comment by ApfelBirneKreis** [comment]
Pls check my changes before merging since this is my first pull request. Sanity Check :D

**Comment by guydavis** [comment]
Thanks, we can try this.  Initially I went looking in the `--help` output from Bladebit for this new parameter and couldn't find it:

image

However, the Bladebit binary's help often lags months behind the actual implementation, with many undocumented features.  So I found this snippet from a changelog that indicates this `--check` option actually does exist in recent versions:

image

I've merged your commit into the current `machinaris:develop` image.  Please give this a try by putting `check_plots: true` in your `bladebit` section of the Settings | Plotting page.  If it works, please share the full plotting log from a plot that is created and then checked.  Thanks!

**Comment by ApfelBirneKreis** [comment]
give me half an hour to finish my current plotting job :D will try after. Thanks for merging! I guess i fuckt it up by committing to main? if i need to change something do i have to commit into compress? 
Sorry for the work im a beginner with github.

**Comment by ApfelBirneKreis** [comment]
@guydavis after updating to `machinaris:develop` im not able to reach the webui anymore. startup logs do not show any discrepancy. Also Console works.

**Comment by guydavis** [comment]
> @guydavis after updating to `machinaris:develop` im not able to reach the webui anymore. startup logs do not show any discrepancy. Also Console works.

Confirmed.  Something broke in an upstream library dependency, preventing the web server from running.  I'll take a look later today.

**Comment by ApfelBirneKreis** [comment]
> > @guydavis after updating to `machinaris:develop` im not able to reach the webui anymore. startup logs do not show any discrepancy. Also Console works.
> 
> Confirmed. Something broke in an upstream library dependency, preventing the web server from running. I'll take a look later today.

No worries. just give me a ping in Discord or comment here to let me know when its time to test :)

**Comment by guydavis** [comment]
Issue was in a new version of the Flask web server, which I have now fixed.

**Comment by ApfelBirneKreis** [comment]
had

> Issue was in a new version of the Flask web server, which I have now fixed.

had to edit the feature plotting was not starting when the argument was not enabled. i tried to fix it in a new commit. there is also an explanation of the new feature here: https://chiaforum.com/t/bladebit-gpu-plotter-beta/19119/594   Comment at Sep 23

Please check the new commit if this could work like that.

**Pull request merged**
